### ISSUE TITLE
Management server is slow to start

### ISSUE THREAD

**Issue by mnajork-palantir** [palantir/witchcraft-go-server#31]
The witchcraft management server sometimes takes a fairly long time (up to 30 seconds) to start after the server start command is issued.

```
DEBUG [2019-01-22T21:31:07.34280755Z] First logline
INFO  [2019-01-22T21:31:16.742606779Z] Listening to https (address: 0.0.0.0:5559, server: management)
[2019-01-22T21:31:19.440819761Z] "GET /status/liveness HTTP/2.0" 503 3 113
[2019-01-22T21:31:23.340134411Z] "GET /status/readiness HTTP/2.0" 503 3 77
```

We're initializing a fairly standard server:

```
return witchcraft.NewServer().
    WithSelfSignedCertificate().
    WithInstallConfigType(config.Install{}).
    WithInstallConfig(installConfig).
    WithRuntimeConfigType(config.Runtime{}).
    WithRuntimeConfigFromFile(viper.GetString(runtimeConfigFlag)).
    WithECVKeyProvider(witchcraft.ECVKeyNoOp()).
    WithOrigin(svc1log.CallerPkg(0, 1)).
    WithInitFunc(func(ctx context.Context, info witchcraft.InitInfo) (cleanup func(), rErr error) {
        // init
    }).Start()
```

**Comment by nmiyake** [comment]
A few things that would be helpful:

* Can you add a timer in your init function to print out the amount of time that it's taking?
* If you run this a few times, what's the general range that you're seeing for this delta? The posted example seems to be about 9 seconds, and the title says up to 30.
* Have you observed that the main server starts running quickly and only the management server takes several seconds to start, or is the startup delayed for both servers?

At the outset, I don't see any reason why it should take the management server this long to start. At the top level, the process is roughly:

(1) Run init function
(2) Construct management server and start it in a separate goroutine
(3) Construct main server and start it in the function

If the user-supplied init function is taking a long time that could slow the startup, but that should impact both management and the regular server.

**Comment by nmiyake** [comment]
Discussed further off-line, and we determined that the observed behavior is most likely due to a call being made in the user-supplied init function -- the user-supplied function was making a network call that could take a long time in some scenarios, and the consumer did not know that the management server is not started until the init function is complete.

To clarify, the user-supplied init function must complete without an error before the server (and management server, if it is separate) are started.
