### ISSUE TITLE
Additional logging during server shutdown

### ISSUE THREAD

**Issue by najork** [palantir/witchcraft-go-server#58]
Logging during server shutdown is currently relatively sparse. Additional logging during shutdown can provide context helpful in debugging issues both within the given service as well as dependencies of the given service.

**Comment by bmoylan** [comment]
Makes sense. Any info you're looking for other than a line like `Shutting down server` with a timestamp?

**Comment by najork** [comment]
@bmoylan nope, that's about it. I was planning on opening a PR with this today.
