### ISSUE TITLE
Change log level of health check content change w/o status change to DEBUG

### ISSUE THREAD

**Issue by najork** [palantir/witchcraft-go-server#93]
Services whose health check contents change frequently (particularly when the check is healthy) produce noisy `INFO`-level logs with these changes. We should consider either emitting the log line at the `DEBUG` level, or emitting the log line at the `DEBUG` level if the check is healthy.

See https://github.com/palantir/witchcraft-go-server/blob/develop/status/status.go#L152

**Comment by nmiyake** [comment]
I'm not sure about this -- I think that having the health status information at INFO can be helpful. The logs being noisy also doesn't seem like a major concern given that filtering out log events/lines is not too hard. Although I don't feel super strongly about this, my gut feeling is that I have a preference for the current behavior over the proposed change.

@bmoylan do you have any thoughts/insight here?

**Comment by najork** [comment]
After thinking about this a bit more, I don't think it makes sense to have it emit the same log line at different levels depending on the health state, and I believe that it's valuable to emit changes to the check contents for unhealthy states. I'm going to close this out since I believe the current behavior handles this properly.
